/**
 ******************************************************************************
 * @file      agr_retarget.c
 * @author    Angel Robotics (XM10)
 * @brief     newlib retargeting that must survive CubeMX code generation.
 *
 *  WHY THIS FILE EXISTS
 *  --------------------
 *  Core/Src/sysmem.c is a CubeMX/CubeIDE-generated file with NO
 *  "USER CODE BEGIN/END" preservation regions, so every "Generate Code" from
 *  the .ioc reverts it to the stock template. Two customizations MUST NOT live
 *  there or they silently vanish on the next regen:
 *
 *    1) _sbrk() heap ceiling. After the Phase-2 stack move, _estack points at
 *       DTCMRAM top while the newlib heap lives in RAM_D1. The stock _sbrk()
 *       bounds a RAM_D1 pointer against the DTCMRAM _estack, so the very first
 *       malloc — including the one _dtoa_r()/float-printf makes — fails, aborts,
 *       and hangs. We bound the heap against RAM_D1's own top (_heap_limit).
 *
 *    2) FreeRTOS-backed newlib retargetable locking, so the shared malloc-heap
 *       arena is safe under concurrent malloc/free (or float printf) from tasks.
 *
 *  HOW IT SURVIVES REGEN
 *  ---------------------
 *  This file is NOT generated by CubeMX — it is ours, so regen never touches it.
 *  We do NOT redefine _sbrk here (that would collide with the stock sysmem.c
 *  _sbrk). Instead the link line carries  -Wl,--wrap=_sbrk , which routes every
 *  reference to _sbrk (from newlib's _sbrk_r, from XM_Lib, everywhere) to
 *  __wrap__sbrk() below. The stock sysmem.c _sbrk becomes __real__sbrk — dead,
 *  unreferenced, harmless — so CubeMX may regenerate sysmem.c freely.
 *
 *    - CMake build:   target_link_options(... -Wl,--wrap=_sbrk)      [CMakeLists.txt]
 *    - CubeIDE build: MCU GCC Linker -> Other flags -> -Wl,--wrap=_sbrk  [.cproject]
 *
 *  The --wrap flag is load-bearing: without it __wrap__sbrk() is never
 *  referenced and -Wl,--gc-sections drops it, so the stock (broken) _sbrk runs.
 *  Verification proxy: if __wrap__sbrk survives in the linked ELF (nm/.map),
 *  --wrap is active (nothing else references that symbol name).
 ******************************************************************************
 */

#include <errno.h>
#include <stdint.h>
#include <sys/lock.h>   /* _LOCK_T + __retarget_lock_* prototypes (retargetable locking) */

#include "stm32h7xx.h"  /* CMSIS core intrinsics (__set_BASEPRI). Explicit: the dev
                        * and SDK projects carry independent include sets, and the
                        * SDK one does not reach CMSIS through FreeRTOS.h. */
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"

/* ==========================================================================
 *  _sbrk() — heap grows in RAM_D1 up to _heap_limit (RAM_D1 top)
 * ==========================================================================
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #  .noinit  #            newlib heap ->                 #
 * ############################################################################
 * ^-- RAM_D1 start                ^-- _end                _heap_limit (RAM_D1 top) --^
 * @endverbatim
 *
 * The MSP stack is NOT in RAM_D1 (it lives at DTCMRAM top, _estack), so the
 * heap cannot collide with it and the ceiling is simply the end of RAM_D1.
 * Both _end and _heap_limit are linker-script symbols (STM32H743XIHX_FLASH.ld).
 * The RAM.ld variant keeps the heap in DTCMRAM and defines _heap_limit as
 * _estack - _Min_Stack_Size; either way the code below is unchanged.
 */
static uint8_t *__sbrk_heap_end = NULL;

void *__wrap__sbrk(ptrdiff_t incr)
{
  extern uint8_t _end;        /* heap start (linker script) */
  extern uint8_t _heap_limit; /* heap ceiling (linker script) */
  const uint8_t *max_heap = (uint8_t *)&_heap_limit;
  uint8_t *prev_heap_end;

  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

/* ==========================================================================
 *  FreeRTOS-backed newlib retargetable locking
 * ==========================================================================
 *  newlib-nano (arm-none-eabi, built with _RETARGETABLE_LOCKING) guards its
 *  global state — most importantly the shared malloc-heap free list
 *  (__lock___malloc_recursive_mutex) — through these __retarget_lock_* hooks.
 *  The toolchain ships them as no-op stubs, so once malloc() actually works
 *  (see _sbrk above) concurrent malloc/free — or a float printf, which calls
 *  _dtoa_r -> malloc — from two tasks could corrupt the heap.
 *
 *  We back every newlib lock with ONE static recursive mutex. Coarse but
 *  correct: newlib holds these locks only briefly, and a recursive mutex lets a
 *  task that already owns it re-enter (newlib may nest different global locks
 *  within one call), so there is no self-deadlock while cross-task access is
 *  serialized.
 *
 *  Safety (thread-safety-audit):
 *   - Before the scheduler starts, execution is single-threaded (main context),
 *     so locking is unnecessary and unsafe (nothing to block on) -> no-op.
 *   - malloc()/float-printf must never run in an ISR; a recursive mutex cannot
 *     be taken from ISR context, so we no-op there defensively.
 *   - The mutex is created eagerly in a startup constructor (single-threaded,
 *     before the scheduler) to avoid any first-acquire creation race.
 */

/* Provide storage for every newlib global lock object so the toolchain's
 * libg_nano lock.o — which bundles these objects together with default no-op
 * lock functions in ONE object file — is never pulled in by the linker.
 * If it were, its functions would collide with ours below (multiple definition,
 * because malloc references the __lock___malloc_recursive_mutex object). newlib
 * only takes the ADDRESS of these objects and hands it back to our lock
 * functions, which ignore it, so the contents are irrelevant. This symbol set
 * matches arm-none-eabi 13.3.1 libg_nano lock.o exactly (nm-verified). */
struct __lock { StaticSemaphore_t reserved; };
struct __lock __lock___malloc_recursive_mutex;
struct __lock __lock___sfp_recursive_mutex;
struct __lock __lock___atexit_recursive_mutex;
struct __lock __lock___at_quick_exit_mutex;
struct __lock __lock___env_recursive_mutex;
struct __lock __lock___tz_mutex;
struct __lock __lock___dd_hash_mutex;
struct __lock __lock___arc4random_mutex;

static StaticSemaphore_t s_newlib_lock_buf;
static SemaphoreHandle_t s_newlib_lock = NULL;

__attribute__((constructor))
static void AGR_NewlibLockCreate(void)
{
  /* Runs from __libc_init_array(), i.e. after SystemInit() but before main(). */
  s_newlib_lock = xSemaphoreCreateRecursiveMutexStatic(&s_newlib_lock_buf);

  /* Why: the create call is NOT pure memory init — xQueueCreateMutexStatic
   *      -> prvInitialiseMutex -> xQueueGenericSend enters and leaves a
   *      FreeRTOS critical section. Before the scheduler starts,
   *      uxCriticalNesting is still its 0xaaaaaaaa sentinel (port.c), so
   *      vPortExitCritical decrements to 0xaaaaaaaa (never 0) and its
   *      mask-restoring branch is skipped. BASEPRI therefore stays at
   *      configMAX_SYSCALL_INTERRUPT_PRIORITY (0x50) for the rest of boot.
   * Impact if omitted: the HAL tick (TIM1_UP, TICK_INT_PRIORITY 15 -> encoded
   *      0xF0 >= 0x50) is masked, so uwTick never increments and the first
   *      blocking HAL delay — inside USB_SetCurrentMode during
   *      MX_USB_OTG_FS_PCD_Init — never returns. The scheduler, which is the
   *      only thing that would clear BASEPRI (vPortSVCHandler), is never
   *      reached: a hard boot hang. (v2.5.0 field failure, fixed in v2.5.1.)
   * What: clear the stale hardware mask directly. This is NOT a critical
   *      section — it only undoes one FreeRTOS failed to undo — so CMSIS is
   *      used rather than the port macros. Safe here: the constructor runs
   *      single-threaded before main, so nothing depends on the mask. */
  __set_BASEPRI(0U);
}

static inline int AGR_NewlibLockUse(void)
{
  /* Engage the shared mutex only where cross-task contention is possible and a
   * mutex op is legal. Skip when:
   *   - not created yet (pre-constructor), or
   *   - scheduler NOT_STARTED (pre-scheduler, single-threaded main context), or
   *   - inside an ISR (a recursive mutex cannot be taken from ISR; malloc/float
   *     printf must never run there anyway).
   * The SUSPENDED state still engages the mutex, but acquire must not BLOCK there
   * (handled below) — a blocking take under vTaskSuspendAll() trips FreeRTOS's
   * "no block while suspended" assert. */
  return (s_newlib_lock != NULL)
      && (xTaskGetSchedulerState() != taskSCHEDULER_NOT_STARTED)
      && (xPortIsInsideInterrupt() == pdFALSE);
}

/* Recursive locks (malloc heap + most newlib global state). */
void __retarget_lock_acquire_recursive(_LOCK_T lock)
{
  (void)lock;
  if (!AGR_NewlibLockUse())
  {
    return;
  }
  if (xTaskGetSchedulerState() == taskSCHEDULER_SUSPENDED)
  {
    /* All tasks suspended by vTaskSuspendAll(): we cannot block (no holder can run
     * to release). A non-blocking take that SUCCEEDS proves exclusivity — no other
     * task can execute to contend. FAILURE means another task holds the arena
     * mid-operation, which is unresolvable here (newlib allocation while the
     * scheduler is suspended AND contended = misuse). Fail deterministically
     * rather than silently claim the lock and corrupt the heap. */
    configASSERT(xSemaphoreTakeRecursive(s_newlib_lock, 0) == pdTRUE);
    return;
  }
  (void)xSemaphoreTakeRecursive(s_newlib_lock, portMAX_DELAY);
}

void __retarget_lock_release_recursive(_LOCK_T lock)
{
  (void)lock;
  if (AGR_NewlibLockUse())
  {
    (void)xSemaphoreGiveRecursive(s_newlib_lock);
  }
}

int __retarget_lock_try_acquire_recursive(_LOCK_T lock)
{
  (void)lock;
  if (!AGR_NewlibLockUse())
  {
    return 1; /* single-threaded / ISR path — treat as acquired */
  }
  /* try-acquire is inherently non-blocking, so it is already SUSPENDED-safe. */
  return (xSemaphoreTakeRecursive(s_newlib_lock, 0) == pdTRUE) ? 1 : 0;
}

/* Non-recursive locks routed to the same recursive mutex (safe: newlib never
 * re-takes a non-recursive lock nested in one task, and same-owner re-entry via
 * a recursive mutex is always permitted). */
void __retarget_lock_acquire(_LOCK_T lock)       { __retarget_lock_acquire_recursive(lock); }
void __retarget_lock_release(_LOCK_T lock)       { __retarget_lock_release_recursive(lock); }
int  __retarget_lock_try_acquire(_LOCK_T lock)   { return __retarget_lock_try_acquire_recursive(lock); }

/* Dynamic lock init/close: a single shared mutex backs every newlib lock, so
 * per-lock objects need no allocation. Point dynamic locks at a non-NULL token
 * (our acquire/release ignore the value) so callers never see an uninit lock. */
void __retarget_lock_init(_LOCK_T *lock)            { if (lock) { *lock = (_LOCK_T)&s_newlib_lock_buf; } }
void __retarget_lock_init_recursive(_LOCK_T *lock)  { if (lock) { *lock = (_LOCK_T)&s_newlib_lock_buf; } }
void __retarget_lock_close(_LOCK_T lock)            { (void)lock; }
void __retarget_lock_close_recursive(_LOCK_T lock)  { (void)lock; }
